site:
  title: AssertJ - fluent assertions java library
  start_page: assertj::index.adoc
  url: /assertj-doc
content:
  sources:
  - url: .
    start_path: docs
    branches: HEAD
  - url: https://github.com/vanroy/assertj-core.git
    start_paths:
      - assertj-core/src/main/docs
      - assertj-guava/src/main/docs
    #tags: [assertj-build-*.*.*]
    branches: [docs-*.*.*]
    version:
      assertj-build-(*.*.*): $1
      docs-(*): $1
  - url: https://github.com/assertj/assertj-db.git
    start_path: src/main/docs
    #tags: [assertj-db-*.*.*]
    branches: [docs-*.*.*]
    version:
      assertj-db-(*.*.*): $1
      docs-(*): $1
ui:
  bundle:
    url: ./ui/build/ui-bundle.zip
asciidoc:
  extensions:
    - '@asciidoctor/tabs'
    - '@springio/asciidoctor-extensions'
  attributes:
    stackoverflow-url: https://stackoverflow.com/questions/tagged/assertj
    assertj-examples-repo: https://github.com/assertj/assertj-examples
    assertj-javadoc-root: https://www.javadoc.io/doc/org.assertj
    fold: none
    page-pagination: '@'
#    hide-uri-scheme: '@'
#    tabs-sync-option: '@'
#    include-java: 'example$docs-src/main/java/org/springframework/docs'
antora:
  extensions:
    - '@antora/lunr-extension'
    - '@antora/collector-extension'
#   index_latest_only: true
